project:
  type: website

website:
  site-url: https://qiufei.site/web-book
  search: false
  # è®¾ç½®ç½‘ç«™å›¾æ ‡
  favicon: profile.jpg
  # title: "è¯¾ä»¶"
  navbar:
    left:
      - text: "é¦–é¡µ"
        href: https://qiufei.site
    right:
      - text: Ræ•™æ
        href: https://qiufei.site/web-book-r
      # - text: pythonæ•™æ
      #   href: https://qiufei.site/pythonbook
      # - text: supermindæ•™æ
      #   href: https://qiufei.site/supermindbook
      # - text: izhiæ•™æ
      #   href: https://qiufei.site/izhibook
      # - icon: github
      #   href: https://github.com/
      - text: "ç®€ä»‹"
        href: https://github.com/qiufei/qiufei.github.io/blob/main/about.qmd
  # page-footer:
  #   left: ğŸ”‹[![](https://posit.co/wp-content/themes/Posit/assets/images/posit-logo-2024.svg){fig-alt="Posit" width=65px}](https://posit.co)
  #   center: 
  #     - text: "é‚±é£ &copy; 2008-2024"
  #     - text: "æµ™ICPå¤‡ 2024072710å·-1"
  #       href: "https://beian.miit.gov.cn"
  #     - text: "æµ™å…¬ç½‘å®‰å¤‡ 33021202002511å·"
  #       href: "http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=33021202002511"
  #   right:
  #     - icon: envelope-at-fill
  #       href: mailto:hfutqiufei@163.com
  #     # - text: â†
metadata-files:
  - https://github.com/qiufei/qiufei.github.io/blob/main/page-footer.yml

format:
  html:
    theme:
     light: journal
     dark: cyborg
    css: styles.css

execute:
  freeze: auto



